<a href="https://colab.research.google.com/github/Maxim687/Machine-learning/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_1_%D0%A2%D0%B8%D0%BC%D0%BE%D1%89%D1%83%D0%BA_%E2%84%9629.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
#Завдання 1
#Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів натуральних чисел, починаючи з 2, та виведіть його значення.

import numpy as np
import math

# кількість факторіалів, які потрібно обчислити
n = 10  # Наприклад, перші 10 факторіалів

# масив натуральних чисел починаючи з 2
numbers = np.arange(2, n+2)

# факторіали цих чисел
factorials = np.array([math.factorial(num) for num in numbers])

# обернені значення факторіалів
inverse_factorials = 1 / factorials

print(inverse_factorials)


[5.00000000e-01 1.66666667e-01 4.16666667e-02 8.33333333e-03
 1.38888889e-03 1.98412698e-04 2.48015873e-05 2.75573192e-06
 2.75573192e-07 2.50521084e-08]


In [ ]:
#Завдання 2
#Створіть одновимірний масив (матрицю) розміром 3х3, заповніть його оберненими значеннями синусів кожного натурального числа, починаючи з 1, та виведіть його значення.

import numpy as np

# масив з 9 натуральних чисел (від 1 до 9)
numbers = np.arange(1, 10)

# синуси цих чисел
sinus = np.sin(numbers)

# обернені значення синусів
inverse_sinus = 1 / sinus

# перетворення масиву в матрицю 3х3
matrix_3x3 = inverse_sinus.reshape(3, 3)

print(matrix_3x3)


[[ 1.18839511  1.09975017  7.0861674 ]
 [-1.32134871 -1.04283521 -3.57889955]
 [ 1.52210106  1.01075622  2.42648664]]


In [ ]:
#Завдання 3
#Створіть масив розміром 4х4, заповніть його випадковими натуральними від 1 до 50 та знайдіть суму елементів кожного рядка.

import numpy as np

# масив розміром 4x4, заповнений випадковими натуральними числами від 1 до 50
matrix_4x4 = np.random.randint(1, 51, size=(4, 4))

# сума елементів кожного рядка
row_sums = np.sum(matrix_4x4, axis=1)

print("Масив 4x4:")
print(matrix_4x4)
print("\nСума елементів кожного рядка:")
print(row_sums)


Масив 4x4:
[[11 47 31 16]
 [ 6  1 24  4]
 [30 23 24 31]
 [ 2 36 40 41]]

Сума елементів кожного рядка:
[105  35 108 119]


In [ ]:
#Завдання 4
#Створіть масив розміром 3х3, заповніть його випадковими дійсними числами в діапазоні від -1.5 до 1.5 та виведіть його значення.

import numpy as np

# масив розміром 3x3, заповнений випадковими дійсними числами в діапазоні від -1.5 до 1.5
matrix_3x3 = np.random.uniform(-1.5, 1.5, size=(3, 3))

print("Масив 3x3 з випадковими дійсними числами від -1.5 до 1.5:")
print(matrix_3x3)


Масив 3x3 з випадковими дійсними числами від -1.5 до 1.5:
[[-0.86853955  0.36368803 -0.24683031]
 [ 1.41396766  0.08378489 -0.64603362]
 [ 0.98242776  1.37390491  0.22283519]]


In [ ]:
#Завдання 5
#Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від 8 до 12 та виконайте на них поелементні операції додавання, віднімання та множення.

import numpy as np

# два одновимірних масиви розміром 4, заповнені випадковими цілими числами в діапазоні від 8 до 12
array1 = np.random.randint(8, 13, size=4)
array2 = np.random.randint(8, 13, size=4)

# поелементне додавання
addition = array1 + array2

# поелементне віднімання
subtraction = array1 - array2

# поелементне множення
multiplication = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)

print("\nРезультат поелементного додавання:", addition)
print("Результат поелементного віднімання:", subtraction)
print("Результат поелементного множення:", multiplication)


Масив 1: [12 10 10  9]
Масив 2: [ 8 12 11 12]

Результат поелементного додавання: [20 22 21 21]
Результат поелементного віднімання: [ 4 -2 -1 -3]
Результат поелементного множення: [ 96 120 110 108]


In [ ]:
#Завдання 6
#Створіть дві матриці 4х4, заповніть їх довільними цілими числами від 1 до 15 та знайдіть їх добуток.

import numpy as np

# дві матриці розміром 4x4, заповнені випадковими цілими числами в діапазоні від 1 до 15
matrix1 = np.random.randint(1, 16, size=(4, 4))
matrix2 = np.random.randint(1, 16, size=(4, 4))

# добуток двох матриць
matrix_dobutok = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

print("\nДобуток матриць:")
print(matrix_dobutok)


Матриця 1:
[[15  4  9  3]
 [ 3 14 15 11]
 [ 9  2  2  3]
 [14  3  3  5]]

Матриця 2:
[[ 4  2  1  5]
 [ 1 10 13  4]
 [11  6  9  3]
 [ 4 10  8  3]]

Добуток матриць:
[[175 154 172 127]
 [235 346 408 149]
 [ 72  80  77  68]
 [112 126 120 106]]


In [ ]:
#Завдання 7
#Створіть дві матриці розміром 4х2 та 2х2, заповніть їх випадковими цілими числами в діапазоні від 1 до 3 та перемножте їх між собою.

import numpy as np

# дві матриці розміром 4х2 та 2х2
matrix1 = np.random.randint(1, 4, size=(4, 2))
matrix2 = np.random.randint(1, 4, size=(2, 2))

# множення матриць
matrix_dobutok = np.dot(matrix1, matrix2)

print("Матриця 1 (4x2):")
print(matrix1)

print("\nМатриця 2 (2x2):")
print(matrix2)

print("\nДобуток матриць:")
print(matrix_dobutok)

Матриця 1 (4x2):
[[2 1]
 [1 1]
 [2 3]
 [1 1]]

Матриця 2 (2x2):
[[2 3]
 [3 1]]

Добуток матриць:
[[ 7  7]
 [ 5  4]
 [13  9]
 [ 5  4]]


In [ ]:
#Завдання 8
#Створіть матрицю розміром 2х2, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

import numpy as np

# матриця розміром 2x2, заповнена випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(2, 2))

# обернена матрицю
# перевірка чи має матриця ненульовий детермінант
if np.linalg.det(matrix) != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:")
    print(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("Матриця є виродженою, обернену матрицю знайти неможливо.")




Матриця:
[[3 2]
 [4 9]]

Обернена матриця:
[[ 0.47368421 -0.10526316]
 [-0.21052632  0.15789474]]


In [ ]:
#Завдання 9
#Створіть матрицю розміром 3х3, заповніть її випадковими дійсними числами в діапазоні від -4 до 10 та транспонуйте її.

import numpy as np

# матриця розміром 3x3, заповнена випадковими дійсними числами в діапазоні від -4 до 10
matrix = np.random.uniform(-4, 10, size=(3, 3))

# транспонування матриці матрицю
transposed_matrix = matrix.T

print("Матриця 3x3:")
print(matrix)

print("\nТранспонована матриця:")
print(transposed_matrix)


Матриця 3x3:
[[ 7.19704002  6.44805051  8.20711126]
 [ 0.3625784   8.26069223  6.87375466]
 [-2.38930146 -2.82846487 -2.50129241]]

Транспонована матриця:
[[ 7.19704002  0.3625784  -2.38930146]
 [ 6.44805051  8.26069223 -2.82846487]
 [ 8.20711126  6.87375466 -2.50129241]]


In [ ]:
#Завдання 10
#Створіть матрицю розміром 3х4 та вектор розміром 4х1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

import numpy as np

# матриця розміром 3x4, заповнену випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 4))

# вектор розміром 4x1, заповнений випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=(4, 1))

# добуток матриці на вектор
dobutok = np.dot(matrix, vector)

print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(dobutok)


Матриця 3x4:
[[0.23978007 0.67262281 0.32804714 0.71339351]
 [0.15188975 0.00186132 0.75223683 0.92064797]
 [0.51952378 0.52616878 0.73852931 0.77208957]]

Вектор 4x1:
[[0.18555555]
 [0.64014997]
 [0.09213466]
 [0.76322334]]

Добуток матриці на вектор:
[[1.04977508]
 [0.80134261]
 [1.09054838]]


In [ ]:
#Завдання 11
#Створіть матрицю розміром 2х3 та вектор розміром 3х1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами від 0 до 1, і знайдіть добуток матриці на вектор.

import numpy as np

# матриця розміром 2x3, заповнену випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(2, 3))

# вектор розміром 3x1, заповнений випадковими цілими числами від 0 до 1
vector = np.random.randint(0, 2, size=(3, 1))

# добуток матриці на вектор
dobutok = np.dot(matrix, vector)

print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(dobutok)


Матриця 2x3:
[[0.11703665 0.15188508 0.97700605]
 [0.97910203 0.40304369 0.41083786]]

Вектор 3x1:
[[1]
 [0]
 [1]]

Добуток матриці на вектор:
[[1.0940427 ]
 [1.38993988]]


In [ ]:
#Завдання 12
#Створіть дві матриці розміром 3х3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть відношення всіх елементів першої матриці до відповідних елементів другої матриці (поелементне ділення).

import numpy as np

# дві матриці розміром 3x3, заповнені випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

# поелементне ділення першої матриці на другу
elementwise_division = matrix1 / matrix2

print("Матриця 1 (3x3):")
print(matrix1)

print("\nМатриця 2 (3x3):")
print(matrix2)

print("\nПоелементне ділення матриць:")
print(elementwise_division)


Матриця 1 (3x3):
[[1 4 4]
 [1 5 5]
 [5 2 4]]

Матриця 2 (3x3):
[[3 3 1]
 [5 2 4]
 [2 1 4]]

Поелементне ділення матриць:
[[0.33333333 1.33333333 4.        ]
 [0.2        2.5        1.25      ]
 [2.5        2.         1.        ]]


In [ ]:
#Завдання 13
#Створіть дві матриці розміром 4х4, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть різницю їх елементів.

import numpy as np

# дві матриці розміром 4x4, заповнені випадковими дійсними числами від 0 до 1
matrix1 = np.random.uniform(0, 1, size=(4, 4))
matrix2 = np.random.uniform(0, 1, size=(4, 4))

# поелементна різниця матриць
elementwise_difference = matrix1 - matrix2

print("Матриця 1 (4x4):")
print(matrix1)

print("\nМатриця 2 (4x4):")
print(matrix2)

print("\nПоелементна різниця матриць:")
print(elementwise_difference)


Матриця 1 (4x4):
[[0.7143009  0.75691216 0.26449151 0.37831954]
 [0.3206772  0.56366213 0.41720339 0.48299611]
 [0.02956681 0.92549901 0.82821172 0.44599139]
 [0.31191301 0.45883838 0.68236707 0.24290113]]

Матриця 2 (4x4):
[[0.15073104 0.41763866 0.13341964 0.88779083]
 [0.51766557 0.58405731 0.033956   0.90159478]
 [0.57786714 0.63885246 0.61861336 0.30748736]
 [0.07427998 0.66174483 0.71866929 0.71637823]]

Поелементна різниця матриць:
[[ 0.56356986  0.3392735   0.13107187 -0.50947129]
 [-0.19698837 -0.02039518  0.38324739 -0.41859867]
 [-0.54830034  0.28664655  0.20959835  0.13850403]
 [ 0.23763303 -0.20290644 -0.03630222 -0.4734771 ]]


In [ ]:
#Завдання 14
#Створіть матрицю розміром 4х4, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі.

import numpy as np

# матриця розміром 4x4, заповнена випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(4, 4))

# побічна діагональ в матриці розміром n x n має індекси (i, n-1-i)
side_diagonal_elements = [matrix[i, matrix.shape[1] - 1 - i] for i in range(matrix.shape[0])]

# сума елементів побічної діагоналі
sum_side_diagonal = np.sum(side_diagonal_elements)

print("Матриця 4x4:")
print(matrix)

print("\nСума елементів побічної діагоналі:")
print(sum_side_diagonal)


Матриця 4x4:
[[-8.10512871 -4.34965332  9.69351704 -8.41308829]
 [-9.69378423  5.10062821 -1.67662187 -4.31644719]
 [-8.67194076 -5.50473595  5.90797836  1.63180045]
 [-6.32711661 -6.5129695   2.42699569 -5.62744625]]

Сума елементів побічної діагоналі:
-21.921562720408247


In [ ]:
#Завдання 15
#Створіть матрицю розміром 3х3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму кубів елементів кожного стовпця матриці.

import numpy as np

# матриця розміром 3x3, заповнена випадковими дійсними числами від -1 до 1
matrix = np.random.uniform(-1, 1, size=(3, 3))

# куби елементів матриці
cubes = matrix ** 3

# сума кубів по кожному стовпцю
sum_of_cubes = np.sum(cubes, axis=0)

# перетворення суми кубів у вектор-стовпчик, тобто додання одної вимірності
sum_of_cubes_column_vector = sum_of_cubes.reshape(-1, 1)

print("Матриця 3x3:")
print(matrix)

print("\nКуби елементів матриці:")
print(cubes)

print("\nВектор-стовпчик з сумами кубів кожного стовпця:")
print(sum_of_cubes_column_vector)


Матриця 3x3:
[[ 0.13598646 -0.81441213  0.89390101]
 [-0.08267252 -0.95913226  0.82712419]
 [-0.26183543 -0.58041076  0.21492878]]

Куби елементів матриці:
[[ 2.51470458e-03 -5.40172782e-01  7.14279662e-01]
 [-5.65045696e-04 -8.82339051e-01  5.65864136e-01]
 [-1.79508585e-02 -1.95526834e-01  9.92850208e-03]]

Вектор-стовпчик з сумами кубів кожного стовпця:
[[-0.0160012 ]
 [-1.61803867]
 [ 1.2900723 ]]
